# First module file

[info]
name = "module_1"
authors = [
    "Ryan Lucas"
]

[submission]
submission_type = "executable" # Other options: sources
binary = "binary_name"
compiler = "gcc"
flags = ["-Wall", "-Wextra", "-Werror"]

[test]
test_type = "executable"
binary = "example_binary"
args = [
    [],
    ["Ryan", "Lucas"],
    ["did", "you", "know", "shinigami", "love", "apples"]
]
