[info]
name = "Z_invalid_framework_strlen"
authors = [
    "Ryan Lucas"
]
difficulty = 2 # Scale from 0-100

[submission]
submission_type = "sources"
sources = ["ft_strlen.c"]

[test]
test_type = "unit-test"
sources = ["unit_test.cpp"]
flags = ["-Wall", "-Wextra", "-Werror"]
compiler = "g++"
framework = "catch2" # No catch2 installation specified in test_config2
subject = "ft_strlen.subject"
