# First exam file

exam_type = "specific" # Other options are 'general' or 'all'
pass_grade = 100
max_grade = 100

[info]
name = "exam_1"
authors = [
    "Ryan Lucas"
]

[config]
exam_order = "in_order"
specific_order = ["hello_world"] # Order of questions
point_indexes = [0] # Which index to use for points for question
points = [ # Different point options -> Value can change depending on attempt no
    [100]
]

[time]
hours = 0
minutes = 20
seconds = 0
