[directories]
submit_directory = "tst/resources/rendu_test"
question_directory = "tst/resources/questions"
exam_directory = "tst/resources/exams"
subject_directory = "tst/resources/subjects"
trace_directory = "tst/resources/trace"
