[info]
name = "ft_countdown_sources"
description = "Print numbers from 9 to 0"
authors = [
    "Ryan Lucas"
]
difficulty = 1 # Scale from 0-100

[submission]
submission_type = "sources"
sources = ["ft_countdown.c"]
compiler = "gcc"

[test]
test_type = "sources"
sources = ["ft_countdown.c"]
compiler = "gcc"
subject = "ft_countdown.subject"
args = [
    [],
    ["I'll", "be", "ignored"],
]

