[info]
name = "aff_a"
authors = [
    "Ryan Lucas"
]
difficulty = 4 # Scale from 0-100

[submission]
submission_type = "sources"
sources = ["aff_a.c"]

[test]
test_type = "expected-output"
sources = []
subject = "aff_a.subject"
expected_stdout = "aff_a.out"
expected_stderr = "aff_a.err"
compiler = "gcc"
flags = ["-Wall", "-Wextra", "-Werror"]
args = [
    ["sentences dont need the first letter, they're fine without"],
    ["Ryan"],
    ["did", "you", "know", "shinigami", "love", "apples"],
    ["nothing"],
    ["abc"],
    ["dub0 O a POIL"],
    ["zz sent le poney"],
    [],
]

